import { createEl } from "../../components/createEl";
import { formValidate } from "./formValidate";
import { validateConfirm } from "./validateConfirm";

export function renderPurchaseModal() {
  const overlay = createEl('div', 'overlay')
  const modalWrapper = createEl('div', 'modal__wrapper')
  const modalForm = createEl('form', 'modal__form')
  modalForm.setAttribute('action','#')
  modalForm.setAttribute('id','form')
  const formTitle = createEl('h3', 'modal__form-title', 'Personal details')
  const personal = createEl('div', 'modal__form-personal')

  const personalName = createEl('div', 'modal__form-item')
  const personalNameLabel = createEl('label', 'modal__form-label')
  personalNameLabel.setAttribute('for', 'form-name')
  const personalNameInput = createEl('input', 'modal__form-input')
  personalNameInput.classList.add('_personal-name')
  personalNameInput.classList.add('_req-personal')
  personalNameInput.setAttribute('id', 'form-name')
  personalNameInput.setAttribute('type', 'text')
  personalNameInput.setAttribute('placeholder', 'name')
  personalNameInput.setAttribute('autocomplete', 'off')

  const personalPhone = createEl('div', 'modal__form-item')
  const personalPhoneLabel = createEl('label', 'modal__form-label')
  personalPhoneLabel.setAttribute('for', 'form-phone')
  const personalPhoneInput = createEl('input', 'modal__form-input')
  personalPhoneInput.classList.add('_personal-phone')
  personalPhoneInput.classList.add('_req-personal')
  personalPhoneInput.setAttribute('id', 'form-phone')
  personalPhoneInput.setAttribute('type', 'text')
  personalPhoneInput.setAttribute('placeholder', 'phone number')
  personalPhoneInput.setAttribute('autocomplete', 'off')

  const personalAddress = createEl('div', 'modal__form-item')
  const personalAddressLabel = createEl('label', 'modal__form-label')
  personalAddressLabel.setAttribute('for', 'form-address')
  const personalAddressInput = createEl('input', 'modal__form-input')
  personalAddressInput.classList.add('_personal-address')
  personalAddressInput.classList.add('_req-personal')
  personalAddressInput.setAttribute('id', 'form-address')
  personalAddressInput.setAttribute('type', 'text')
  personalAddressInput.setAttribute('placeholder', 'address')
  personalAddressInput.setAttribute('autocomplete', 'off')

  const personalEmail = createEl('div', 'modal__form-item')
  const personalEmailLabel = createEl('label', 'modal__form-label')
  personalEmailLabel.setAttribute('for', 'form-email')
  const personalEmailInput = createEl('input', 'modal__form-input')
  personalEmailInput.classList.add('_personal-email')
  personalEmailInput.classList.add('_req-personal')
  personalEmailInput.setAttribute('id', 'form-email')
  personalEmailInput.setAttribute('type', 'text')
  personalEmailInput.setAttribute('placeholder', 'e-mail')
  personalEmailInput.setAttribute('autocomplete', 'off')
  
  const formTitleCard = createEl('h3', 'modal__form-title', 'Credit card details')
  const paymentCard = createEl('div', 'modal__form-card')
  const paymentCardTopBlock = createEl('div', 'modal__form-card-block')
  const paymentCardImg = createEl('img', 'modal__form-card-img')
  paymentCardImg.setAttribute('src', './assets/image/card-payment.svg')
  paymentCardImg.setAttribute('alt', 'Payment card')
  const paymentCardNumber = createEl('div', 'modal__form-item')

  const paymentCardNumberInput = createEl('input', 'modal__form-input')
  paymentCardNumberInput.classList.add('_card-number')
  paymentCardNumberInput.classList.add('_req-card')
  paymentCardNumberInput.setAttribute('id', 'form-card-number')
  paymentCardNumberInput.setAttribute('type', 'text')
  paymentCardNumberInput.setAttribute('placeholder', 'card number')
  paymentCardNumberInput.setAttribute('autocomplete', 'off')

  const paymentCardBottomBlock = createEl('div', 'modal__form-card-block')
  const paymentCardValid = createEl('div', 'modal__form-item')

  const paymentCardValidLabel = createEl('label', 'modal__form-label', 'valid: ')
  paymentCardValidLabel.setAttribute('for', 'form-card-valid')
  const paymentCardValidInput = createEl('input', 'modal__form-input')
  paymentCardValidInput.classList.add('_card-valid')
  paymentCardValidInput.classList.add('_req-card')
  paymentCardValidInput.setAttribute('id', 'form-card-valid')
  paymentCardValidInput.setAttribute('type', 'text')
  paymentCardValidInput.setAttribute('placeholder', 'valid thru')
  paymentCardValidInput.setAttribute('autocomplete', 'off')

  const paymentCardCvv = createEl('div', 'modal__form-item')

  const paymentCardCvvLabel = createEl('label', 'modal__form-label', 'cvv: ')
  paymentCardCvvLabel.setAttribute('for', 'form-card-cvv')
  const paymentCardCvvInput = createEl('input', 'modal__form-input')
  paymentCardCvvInput.classList.add('_card-cvv')
  paymentCardCvvInput.classList.add('_req-card')
  paymentCardCvvInput.setAttribute('id', 'form-card-cvv')
  paymentCardCvvInput.setAttribute('type', 'number')
  paymentCardCvvInput.setAttribute('placeholder', 'cvv')
  paymentCardCvvInput.setAttribute('autocomplete', 'off')

  const btnConfirm = createEl('button', 'modal__form-btn-confirm', 'confirm')

  personalName.appendChild(personalNameLabel)
  personalName.appendChild(personalNameInput)
  personalPhone.appendChild(personalPhoneLabel)
  personalPhone.appendChild(personalPhoneInput)
  personalAddress.appendChild(personalAddressLabel)
  personalAddress.appendChild(personalAddressInput)
  personalEmail.appendChild(personalEmailLabel)
  personalEmail.appendChild(personalEmailInput)
  personal.appendChild(personalName)
  personal.appendChild(personalPhone)
  personal.appendChild(personalAddress)
  personal.appendChild(personalEmail)

  paymentCardTopBlock.appendChild(paymentCardImg)
  paymentCardNumber.appendChild(paymentCardNumberInput)
  paymentCardTopBlock.appendChild(paymentCardNumber)
  paymentCardValid.appendChild(paymentCardValidInput)
  paymentCardCvv.appendChild(paymentCardCvvInput)

  paymentCardValidLabel.appendChild(paymentCardValid)
  paymentCardCvvLabel.appendChild(paymentCardCvv)
  paymentCardBottomBlock.appendChild(paymentCardValidLabel)
  paymentCardBottomBlock.appendChild(paymentCardCvvLabel)

  paymentCard.appendChild(paymentCardTopBlock)
  paymentCard.appendChild(paymentCardBottomBlock)
  modalForm.appendChild(formTitle)
  modalForm.appendChild(personal)
  modalForm.appendChild(formTitleCard)
  modalForm.appendChild(paymentCard)
  modalWrapper.appendChild(modalForm)
  modalWrapper.appendChild(btnConfirm)
  overlay.appendChild(modalWrapper)
  document.body.appendChild(overlay)

  overlay.addEventListener('click', (event: Event) => {
    if (event.target instanceof HTMLDivElement) {
      if (event.target.classList.contains('overlay')) document.body.removeChild(overlay)
    }
  })

  btnConfirm.addEventListener('click', validateConfirm)

  if (modalForm instanceof HTMLFormElement) formValidate(modalForm)
}